main: "com.minecraft_among_us.plugin.Plugin"
name: "MinecraftAmongUs"
version: "1.0.0"
authors: ["Lelberto", "MrPopop69"]
api-version: "1.16"
commands:
  test:
    description: "Test command for MinecraftAmongUs plugin"
    usage: "/test"
